language: python

python:
- 2.7
- 3.4
- 3.5

install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O mc.sh
- bash mc.sh -b -p ~/miniconda
- export PATH=~/miniconda/bin:$PATH
- |
  echo "channels:
  - conda-forge
  -  defaults
  always_yes: True" > ~/.condarc
- export CONDARC=~/.condarc
- conda install python=$TRAVIS_PYTHON_VERSION pip conda-build
- conda update --all
- pip install -r test-requirements.txt
- pip install codecov

script:
- coverage run -m pytest -vrsx

after_success:
- codecov
