language: python

python:
- 2.7
- 3.4
- 3.5

install:
- git clone https://github.com/ericdill/ci ~/scripts
- . ~/scripts/install-miniconda.sh
- conda install python=$TRAVIS_PYTHON_VERSION pip conda-build
- conda update --all
- pip install -r test-requirements.txt
- pip install codecov
- pip install -e .

script:
- ./run_tests

after_success:
- codecov
